//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Category { get; set; }
        public string RangeBrand { get; set; }
        public string Brand { get; set; }
        public int TV { get; set; }
        public int Print { get; set; }
        public int Radio { get; set; }
        public int Digital { get; set; }
        public int OOH { get; set; }
        public int BTL { get; set; }
        public int Total { get; set; }
    }
}
